### ISSUE TITLE
App is able to display notifications for 'critical' eCO2 levels in registered locations

### ISSUE THREAD

**Issue by robooooo** [spe-uob/CO2Monitor#13]

**Comment by sowelilili** [comment]
This is probably done as of 43d543fe59aa219651e15a3001e7624d7de5c265, but let's wait until it's properly tested and hooked up to the API before closing it, just in case.

**Comment by sowelilili** [comment]
Augmented this with 52ebd0c7804690e67cc57acbc9eacc875a748fba and c0cb56e46a207c0084173b5fb1bdc0bf57044844, and now it's been tested.
